START cmd.exe /k ""C:\Program Files (x86)\mosquitto\mosquitto.exe""
START cmd.exe /k ""C:\Program Files (x86)\mosquitto\mosquitto_sub.exe" -h localhost -t ELECTREE-43BF713C/status"
START cmd.exe /k ""C:\Program Files (x86)\mosquitto\mosquitto_sub.exe" -h localhost -t ELECTREE-43BF713C/debug"
START cmd.exe /k ""C:\Program Files (x86)\mosquitto\mosquitto_sub.exe" -h localhost -t ELECTREE-43BF713C/uartin"
START cmd.exe /k ""C:\Program Files (x86)\mosquitto\mosquitto_sub.exe" -h localhost -t ELECTREE-43BF713C/conf"
START cmd.exe /k ""C:\Program Files (x86)\mosquitto\mosquitto_pub.exe" -h localhost -t ELECTREE-43BF713C/relay/7/set -m 0"